name: Regular Deployment

on:
  schedule:
    - cron: "0 18 * * *" # 3:00 AM JST

jobs:
  build:
    name: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Call the web hook
      run: curl -X POST ${{ secrets.DEPLOY_TRIGGER_URL }}
